name: Auto Bump & Tag

on:
  pull_request:
    types:
      - closed

jobs:
  bump-version-and-tag:
    if: github.event.pull_request.merged == true && github.base_ref == 'master'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack (for Yarn 4)
        run: corepack enable

      - name: Determine bump type from PR labels
        id: bump_type
        run: |
          LABELS=$(echo '${{ toJson(github.event.pull_request.labels) }}' | jq -r '.[].name' | tr '[:upper:]' '[:lower:]')
          echo "Labels: $LABELS"

          if echo "$LABELS" | grep -q "major"; then
            echo "type=major" >> $GITHUB_OUTPUT
          elif echo "$LABELS" | grep -Eq "minor|feature"; then
            echo "type=minor" >> $GITHUB_OUTPUT
          elif echo "$LABELS" | grep -Eq "patch|fix"; then
            echo "type=patch" >> $GITHUB_OUTPUT
          else
            echo "No bump label found, defaulting to patch"
            echo "type=patch" >> $GITHUB_OUTPUT
          fi

      - name: Configure Git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Bump version and create tag
        run: |
          BUMP_TYPE=${{ steps.bump_type.outputs.type }}
          echo "Bumping version with type: $BUMP_TYPE"

          yarn version $BUMP_TYPE
          NEW_VERSION=$(jq -r '.version' package.json)
          echo "New version: $NEW_VERSION"

          git add package.json yarn.lock
          git commit -m "chore(release): v$NEW_VERSION [skip ci]"
          git tag "v$NEW_VERSION"
          git push origin master --tags
